openapi: 3.0.0
info:
  version: "0.1"
  title: Simple Password Generator
  description: API endpoint to generate a simple password
servers:
  - url: https://some-url.com
    description: Test server

paths:

  /simple_password:
    get:
      tags:
        - Simple Password
      description: | 
        Returns a simple password string  
        Examples: 
        ```indigo-OXYGEN-lion6```
        ```MAROON#helium#jellyfish84```
        ```darkred*neon*RABBIT10```
      x-badges:
        - color: green
          label: "User registration"
      responses:
        200:
          description: OK
          headers:
            Access-Control-Allow-Headers:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SimplePasswordResponse"
        401:
          description: Unauthorized
          headers:
            Access-Control-Allow-Headers:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        403:
          description: Forbidden
          headers:
            Access-Control-Allow-Headers:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: Internal Server Error
          headers:
            Access-Control-Allow-Headers:
              schema:
                type: string
            Access-Control-Allow-Methods:
              schema:
                type: string
            Access-Control-Allow-Origin:
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - cognitoUsers: []
      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SimplePasswordGet.Arn}/invocations
        passthroughBehavior: when_no_match
        httpMethod: POST
        type: aws_proxy

components:
  schemas:

    Success:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The response message

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The error message

    SimplePasswordResponse:
      type: object
      required:
        - simple_password
      properties:
        simple_password:
          description: Three words (one CAPS, randomised), separated by a random punctuation character `!#$%&*+-<=>?@_` and ending with a number 0-99
          type: string
          example: "indigo-OXYGEN-lion5"
